### ISSUE TITLE
I don't know how to use this code

### ISSUE THREAD

**Issue by heerduo** [dfdazac/wassdistance#1]
Thanks a lot for your work. But I don't know how to use this code, it does not like python main.py?

**Comment by dfdazac** [comment]
Hi, thank you for appreciating the code in this repository. The code that contains the layer to compute Wasserstein distances is in `layers.py`, and an example on how to use it is in the notebook `sinkhorn.ipynb`. Perhaps this could work as a guide to incorporate it into your own work.
